name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source: '.'
          target: '.'
