name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source: 'deploy.tar'
          target: '.'
      - name: Run a multi-line script
        run: |
          tar -xf deploy.tar
