name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source: 'deploy.tar'
          target: '.'
          
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: ${{ format('{0}@{1}:22', secrets.SSH_USER, secrets.HOST) }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: false
          command: |
            tar -xf deploy.tar
            echo "I am $NAME"
